config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('exam.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from .views import *

app_name = 'exam'

urlpatterns = [
    path('', show_certificates, name='certificates'),
    path('certificate=<int:id>/', show_tests, name='tests'),
    path('test=<int:id>/', show_detail, name='detail'),
    path('report=<int:id>/', show_report, name='report'),
    path('save=<int:id>/', save_report, name='save')
]

exam/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
'''
odict_keys(['CERTIFICATE_ID', 'NAME'])
odict_keys(['CERTIFICATE_ID', 'TEST_ID', 'YEAR', 'NUM'])
odict_keys(['TEST_ID', 'QUESTION_ID', 'QUESTION_NUM', 'CONTENTS', 'ANSWER', 'IMG'])
odict_keys(['QUESTION_ID', 'CHOICE_ID', 'CHOICE_NUM', 'CHOICE_CONTENTS', 'IMG'])
'''
class Certificate(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('exam:tests', args=[self.id])

class Subject(models.Model):
    certificate = models.ForeignKey(Certificate, on_delete=models.CASCADE, related_name='subjects')
    order = models.PositiveIntegerField()
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.certificate.name + '_' + str(self.order) + '_' + self.name

    def range(self):
        return [20*(self.order-1)+1, 20*self.order]


class Test(models.Model):
    certificate = models.ForeignKey(Certificate, on_delete=models.CASCADE, related_name='tests')
    year = models.PositiveIntegerField()
    num = models.PositiveIntegerField()

    def __str__(self):
        return "{}년 {}회차".format(self.year, self.num)

    def get_absolute_url(self):
        return reverse('exam:detail', args=[self.id])

    def subjects(self):
        subjects = Subject.objects.filter(certificate_id=self.certificate_id, order__in=self.selected_subjects)
        new_subjects = []
        for subject in subjects:
            subject.questions = Question.objects.filter(test_id=self.id, question_num__range=subject.range())
            new_subjects.append(subject)
        return new_subjects

    def marking(self, answer):
        self.point = 0
        self.o = []
        self.x = []
        for subject in self.subjects():
            subject.point = 0
            subject.o = []
            subject.x = []
            for question in subject.questions:
                user_ans = answer.get(str(question.question_num))
                if user_ans:
                    question.checked = int(user_ans)
                if question.answer == None or str(question.answer) != user_ans:
                    subject.x.append(question)
                else:
                    subject.o.append(question)
                    subject.point += 1
            self.point += subject.point
            self.o += subject.o
            self.x += subject.x

    def get_selected_questions(self):
        questions = []
        for subject in self.subjects():
            questions += subject.questions
        return questions


class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name='questions')
    question_num = models.PositiveIntegerField()
    contents = models.CharField(max_length=200)
    answer = models.PositiveIntegerField()
    img = models.ImageField(upload_to='questions/%Y/%m/%d', blank=True)

    def __str__(self):
        return str(self.test_id) + " {}번문제".format(self.question_num)

    def get_answer(self):
        special_characters=['①','②','③','④']
        return special_characters[self.answer-1]




class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_num = models.PositiveIntegerField()
    contents = models.CharField(max_length=200)
    img = models.ImageField(upload_to='choices/%Y/%m/%d', blank=True)

    def __str__(self):
        return str(self.question_id) + " 보기{}".format(self.choice_num)

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    created = models.DateTimeField(auto_now_add=True)

class SubmitQuestion(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name='questions')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='submitted')
    answer = models.PositiveIntegerField(null=True)

exam/views.py
from django.shortcuts import render, HttpResponse
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse

def show_certificates(request):
    certificates = Certificate.objects.all()
    return render(request, 'exam/certificates.html', {'select_box':certificates})

def show_tests(request, id):
    tests = Test.objects.filter(certificate_id=id)
    subjects = Subject.objects.filter(certificate_id=id)
    return render(request, 'exam/tests.html', {'select_box':tests, 'check_box':subjects})


def show_detail(request, id):
    subjects = [int(selected) for selected in request.GET]
    request.session['selected_subjects'] = subjects
    test = Test.objects.get(id=id)
    test.selected_subjects = subjects

    return render(request, 'exam/detail.html', {'test':test})


def show_report(request, id):
    if request.method == 'POST':
        test = Test.objects.get(id=id)
        #session content 만들기 .. 다음뷰에서 저장하면 세션딕셔너리를 그대로 저장.. report 모델에..
        test.selected_subjects = request.session['selected_subjects']
        test.marking(request.POST)

        request.session['answer'] = request.POST

        return render(request, 'exam/report.html', {'test': test})
    else:
        return HttpResponseRedirect(reverse('exam:detail',args=[id]))

def save_report(request, id):
    if request.method == 'POST' and request.session['answer']:
        report = Report(user_id=request.POST['user_id'])
        report.save()

        test = Test.objects.get(id=id)
        test.selected_subjects = request.session['selected_subjects']
        questions = test.get_selected_questions()

        for question in questions:
            ans = request.session['answer'].get(str(question.question_num))
            if ans:
                ans = int(ans)
            SubmitQuestion(report_id=report.id, question=question, answer=ans).save()

        request.session['answer'] = None
        return HttpResponse("저장되었습니다.")
    else:
        return HttpResponseRedirect(reverse("exam:certificate"))

exam/templates/exam/certificates.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align:center; ">
    <select id="select_box">
        <option value="">선택</option>
        {% for val in select_box %}
            <option value="{{val.get_absolute_url}}">{{val}}</option>
        {% endfor %}
    </select>
    <button href="#" onclick="location.href = get_selected_val()">다음으로</button>
    <script type="text/javascript">
        function get_selected_val(){
            var target = document.getElementById("select_box");
            return target.options[target.selectedIndex].value;
        }
    </script>
</div>

{% endblock %}

exam/templates/exam/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{test.certificate.name}} {{test}}</h1>
<ul class="nav nav-tabs">
    {% for subject in test.subjects %}
        <li class="nav-item">
        <a class="nav-link {%if subject.order is test.subjects.0.order %}active{%endif%}" data-toggle="tab" href="#tab{{subject.order}}">{{subject.order}}.{{subject.name}}</a>
        </li>
    {% endfor %}
</ul>

<form method="post" action="{% url 'exam:report' test.id %}">
    {%csrf_token%}
        <div class="tab-content">
            {% for subject in test.subjects %}
                <div class="tab-pane fade {% if subject.order is test.subjects.0.order %}show active{% endif %}" id="tab{{subject.order}}">
                    {% for question in subject.questions %}
                        {% include 'question.html'%}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    <div style="text-align:center;">
        <button type="submit">채점하기</button>
    </div>

</form>

{% endblock %}

exam/templates/exam/report.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{test.certificate.name}} {{test}} 채점결과</h1>
    <h2>{{test.point}}</h2>
    <h2 style="color:blue; margin-top:100px;">여기서부턴 맞춘문제 입니다.</h2>
    {% for question in test.o %}
        {% include 'checked_question.html' %}
    {% endfor %}

    <h2 style="color:red; margin-top:100px;">여기서부턴 틀린문제 입니다.</h2>
    {% for question in test.x %}
        {% if question.checked %}
            {% include 'checked_question.html' %}
        {% endif %}
    {% endfor %}

    <h2 style="color:red; margin-top:100px;">여기서부턴 풀지않은 문제 입니다.</h2>
    {% for question in test.x %}
        {% if not question.checked %}
            {% include 'checked_question.html' %}
        {% endif %}
    {% endfor %}
    <form action="{% url 'exam:save' test.id%}" method="post">
        {% csrf_token %}
        <input type="hidden"  name="user_id" value="{{user.id}}">
        <button type="submit">저장하기</button>
    </form>
{% endblock %}

exam/templates/exam/tests.html
{% extends 'base.html' %}
{% block content %}

<select id="select_box">
    <option value="">선택</option>
    {% for val in select_box %}
        <option name="{{val.get_absolute_url}}" value="{{val.get_absolute_url}}">{{val}}</option>
    {% endfor %}
</select>
<form method="get" onsubmit="get_url()" id="frm">
    {% for subject in check_box %}
        <div class="custom-control custom-checkbox">
            <input id="{{subject.order}}" type="checkbox" checked
               name="{{subject.order}}" value="true" class="custom-control-input">
            <label for="{{subject.order}}" class="custom-control-label">
            {{subject.order}}. {{subject.name}}
            </label>
        </div>
    {% endfor %}
    <button onclick="">다음으로</button>
</form>
<script type="text/javascript">
    function get_selected_val(){
        var target = document.getElementById("select_box");
        return target.options[target.selectedIndex].value;
    }

    function get_url(){
        var f = document.getElementById("frm");
        f.action = get_selected_val()
    }
</script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>detail</title>
</head>
<body>
            <div style="text-align:center;" >
                <div style="padding:50px; width: 900px; display:inline-block; text-align:left;"class="bg-light">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">모의고사</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        {% endif %}
                    </li>

                </ul>
            </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</body>
</html>

templates/checked_question.html
<p style="margin-bottom:100px;">
    <p>{{question.question_num}}. {{question.contents}}

        <span style="color:blue; text-weight:bold;">정답{{question.get_answer}}</span></p>

    {% if question.img %}
        <p>
            <img src="{{question_set.question.img.url}}">
        </p>
    {% endif %}

    {% for choice in question.choices.all %}
        <p style="padding-left:20px;">
            <div class="custom-control custom-radio">
                <input id="{{question.question_num}}n{{choice.choice_num}}" type="radio" name="{{question.question_num}}" value="{{choice.choice_num}}"
                {% if choice.choice_num == question.checked %} checked  {% endif %} disabled class="custom-control-input">

                <label for="{{question.question_num}}n{{choice.choice_num}}" class="custom-control-label">
                    {{choice.choice_num}}. {{choice.contents}}
                    {% if choice.img %} <img src="{{choice.img.url}}"> {% endif %}
                </label>
            </div>
        </p>

    {% endfor %}
</p>

templates/question.html
<p style="margin-bottom:100px;">

    <!--문제내용-->
    <p>{{question.question_num}}. {{question.contents}}</p>

    <!--그림있으면 그림-->
    {% if question.img %} <p><img src="{{question.img.url}}"></p> {% endif %}

    <!--선택지-->
    {% for choice in question.choices.all %}
        <p style="padding-left:20px;">
                <div class="custom-control custom-radio">
                    <input id="{{question.question_num}}n{{choice.choice_num}}" type="radio"
                       name="{{question.question_num}}" value="{{choice.choice_num}}" class="custom-control-input">
                    <label for="{{question.question_num}}n{{choice.choice_num}}" class="custom-control-label">
                    {{choice.choice_num}}. {{choice.contents}} {% if choice.img %} <img src="{{choice.img.url}}"> {% endif %}
                    </label>
                </div>
        </p>
    {% endfor %}

</p>